### ISSUE TITLE
Support for automated policy refresh

### ISSUE THREAD

**Issue by mbrancato** [Venafi/vault-pki-monitor-venafi#26]
**BUSINESS PROBLEM**
The policies are set currently only at the time of the `vault write pki/venafi-policy/policy-name`. If policies are changed on the Venafi-side, they require a manual refresh.

**PROPOSED SOLUTION**
Have the policy automatically refresh the policy on a defined interval. Support a interval of `0` as the default to maintain legacy no-refresh support.

**CURRENT ALTERNATIVES**
We have to manually refresh - a cron job was proposed.

**VENAFI EXPERIENCE**

**Comment by tr1ck3r** [comment]
Hi @mbrancato this is a feature we've been planning and hope to deliver by the end of March 2020.

**Comment by tr1ck3r** [comment]
Updated ETA for this enhancement is end of April 2020 (development is underway).

**Comment by tr1ck3r** [comment]
@mbrancato apologies for the long delay but I'm pleased to finally report that the enhancement you requested is now available the latest release, [v0.8.1](https://github.com/Venafi/vault-pki-monitor-venafi/releases/tag/v0.8.1), through the `auto_refresh_interval` parameter of the venafi-policy.  Please be aware that the significant configuration changes have been made since the v0.6.0 release to accommodate proper support for TPP token authentication, and to improve both usability and reliability of this solution.  

:sparkles: Please let us know if you run into any challenges upgrading.  We have created a community [Slack workspace](https://join.slack.com/t/venafi-integrations/shared_invite/zt-i8fwc379-kDJlmzU8OiIQOJFSwiA~dg) where Venafi customers and partners can interact directly with each other and the Venafi development, support, and product teams.
