### ISSUE TITLE
Return TPP API errors and document policy requirements

### ISSUE THREAD

**Issue by mbrancato** [Venafi/vault-pki-monitor-venafi#27]
**PROBLEM SUMMARY**
The documentation today does not specify any policy requirements that are incompatible with this plugin. There seems to be at least one setting: `Allow Users to Import Duplicate Certificates and Reuse Private Keys` - this must be set to **yes** if any client using Vault has done a renew operation with the same keypair.

The API was responding:

`Job id: 2 ### could not import certificate: Private key reuse error. The private key is already in use by another certificate. Private keys cannot be shared among certificates. Duplicate DN: ...`

Issues we seem to have solved by allowing this:

Excessive logging of errors on Venafi TPP.
Imported certificates were being shown as not current and were seen in the history of the cert even though they were still valid.
Policy refresh attempts would time out shortly after restarting Vault.

**STEPS TO REPRODUCE**
renew a certificate using the same keypair
Attempt manual policy refresh

**EXPECTED RESULTS**
New certificates to import successfully as the latest
Policy refresh to succeed and not timeout

**ACTUAL RESULTS**
Certs fail to import, when certificates do import they are in the history, Vault API timeouts on policy refresh

**ENVIRONMENT DETAILS**
Vault 1.2.2, Venafi monitor 0.5.1

**COMMENTS/WORKAROUNDS**
There is both a need to document this policy setting in the README as a prerequisite and the ability to return these API `Error` fields to the user through the Vault API / CLI.

The issue occurs here: https://github.com/Venafi/vault-pki-monitor-venafi/blob/f85fe8d8c108a61a57d1862a9411cc139e8e8901/plugin/pki/path_import_queue.go#L267-L275

**Comment by tr1ck3r** [comment]
Thank you @mbrancato.  Can you confirm that you are renewing the certificates that use the same keypair by providing an externally generated CSR (i.e. using `vault write pki/sign/role`)?  As opposed to having vault generate the keypair (i.e. using `vault write pki/issue/role`).

The import feature of this secrets engine is a background process so reporting errors in the Vault log may be the best we can do there but we're investigating.  Currently the import-queue will grow infinitely if certificates that reuse private keys are issued by vault and the policy applied to the target folder in TPP forbids private key reuse.  For cases like this where TPP rejects the import, it may be appropriate to remove the certificate from the queue since the likelihood of it ever importing successfully are near zero.

**Comment by mbrancato** [comment]
> Can you confirm that you are renewing the certificates that use the same keypair by providing an externally generated CSR (i.e. using `vault write pki/sign/role`)? As opposed to having vault generate the keypair (i.e. using `vault write pki/issue/role`).

@tr1ck3r I believe this is correct. We do think this has to do with tools like cert-manager that are utilizing the `pki/sign` API path and not `pki/issue`. That said, it seemed like this issue was causing delays and/or blocking the import of new certs using the `pki/issue` APIs as well.

> The import feature of this secrets engine is a background process so reporting errors in the Vault log may be the best we can do as far as providing awareness but we're investigating.

That is a good point. It was difficult to debug because the CLI would just time out and Vault didn't return any good log data.

> Currently the import-queue will grow infinitely if certificates that reuse private keys are issued by vault and the policy applied to the target folder in TPP forbids private key reuse. For cases like this where TPP rejects the import, it may be appropriate to remove the certificate from the queue since the likelihood of it ever importing successfully are near zero.

We think this queue may have prevented the import of new certs using `pki/issue` as well. Restarts of Vault seemed to help them get imported, but I agree that removal from the queue might be warranted. There seems to be some backoff-retry logic, but it might just retry the whole queue instead of placing new certs first or keeping track of certs that failed to import.

**Comment by mr-tron** [comment]
After importing ~500-1000 certificates our plugin stops importing certificates. It continues signing new certificates, adds them to the queue but stops processing queue.

We can't find problem in plugin so maybe it connected to Vault SDK.
We see gRPC errors
```
handle request: transport=gRPC path= status=finished err="unsupported operation"
status=finished err="rpc error: code = Canceled desc = context canceled"
```
We made docker image for standalone bug reproducing without real tpp. So maybe Hashicorp Team can find solution.
https://github.com/arykalin/bugreproduce/

**Comment by arykalin** [comment]
Some more clarification for hashicorp engineers:  
We starting our import queue in go routine when plugin is activated here:
https://github.com/Venafi/vault-pki-monitor-venafi/blob/humana-bug/plugin/pki/backend.go#L101
after that we're creating wait group and starting gou routine for every role:
https://github.com/Venafi/vault-pki-monitor-venafi/blob/humana-bug/plugin/pki/path_import_queue.go#L129-L178
this routine is creatine worker pool for worker who should import certificates into TPP

For unknown reason at some point workers are stopping to import certificates into TPP

**Comment by kalafut** [comment]
Hi. Thanks for the bug repro repository. That really sped things up and I got to a failing state pretty quickly.

The heavy use of worker pools and buffered channels had me thinking there was a blocked channel of waitgroup somewhere, but I didn't find anything and as far as I can tell that flow looks correct.

I was however able to narrow down the pass/fail condition to the client acquisition here: https://github.com/Venafi/vault-pki-monitor-venafi/blob/42fd90a5249643d0ec8e06aff7b67c7dbf84c4af/plugin/pki/path_import_queue.go#L233
These client objects are being requested in large numbers, but there is no explicit reuse or releasing of the resource. I didn't dig too deeply in to that connection code, but I suspect you're leaking connection resources. I hacked up a quick modification to cache the clients based on config (https://gist.github.com/kalafut/12b325146189b34b50fa4cab63b29aef), and when I ran with that the test script completed. (Normally such caches would be on the backend object, not in the package. This was just a test.)  You're more familiar with the nuances of that connection (e.g. what needs a new one, how they should be refreshed or closed, etc.), but I do think some sort of pool or cache will be needed.  When I was first testing, I'd even commented out the actual calls to tpp and it would still hang just on requesting the client connection.

One other totally unrelated but odd thing occurred when I tried running without the queue goroutine even started, so the certs just built up in the import queue. When I ran `vault list pki/import-queue/`, a handful of the cert sns were missing the last byte. Mostly they're at the end of the list, but a few others in the middle are affected too. I have no idea what that is due to. You can see the list here:  https://gist.github.com/kalafut/2a851cc20a7a6116d025a3bce163d9ea

Hope that helps some.

**Comment by mbrancato** [comment]
To tag on @kalafut's observation on the missing byte - I've noticed this in `vault list pki/certs/` as well with the monitor plugin.

Hopefully the other information provided will be helpful here.

**Comment by tr1ck3r** [comment]
Thank you for the assistance @kalafut, I'm pretty sure the "missing" byte is inconsequential (unless they are non-unique) since, as you said, those are just the serial numbers of the certificates issued by the Vault PKI certificate authority.  @mbrancato is correct that if there is an issued in that area it would affect the native Vault PKI as well because this solution is using the same code unaltered.

We'll be looking into the caching area you highlighted starting today with the intention of providing an updated plugin binary early next week.  Thanks again!

**Comment by mbrancato** [comment]
Sorry, just to clarify... when I reference `pki/` I'm just using this path as the example mount point for the Venafi monitor plugin. I haven't seen this in the built-in pki plugin.

I verified I can read certs listed that are missing the last byte, and when I validate them using `openssl` the serial number is in fact missing the last octet. So it is probably a non-issue on that.

**Comment by mr-tron** [comment]
it's not last byte. it's first 00 byte.

**Comment by mr-tron** [comment]
About resources leak. I fixed leaking tcp connections (via request.Close = true in vcert library), but it doesn't help. Sometimes stress.sh script freezes on one minute, gets error
```Сб фев  1 15:18:04 MSK 2020
>>> 100 in the queue, diff 487, 0 errors occurred so far...
Error writing data to pki-monitor/venafi-policy/default: context deadline exceeded
4e:03:92:42:4e:1d:ba:5f:13:37:e9:40:f1:a5:c7:a9:d1:3a:d9:aa
Сб фев  1 15:19:04 MSK 2020
```
and after that no one certificates imports from queue to TPP.
You can see plugin stack trace in gist. 
https://gist.github.com/mr-tron/ecbddb07c592892b4b61de7a7e4be5f9

And in stack trace I noticed that too many goroutines are waiting io mutex for writing logs to stderr.
``` 
goroutine 19711 [semacquire, 8 minutes]:
 internal/poll.runtime_Semacquire(0xc000075cec)
 	/usr/lib/go-1.13/src/runtime/sema.go:61 +0x42
 internal/poll.(*fdMutex).rwlock(0xc000075ce0, 0x0, 0x40d986)
 	/usr/lib/go-1.13/src/internal/poll/fd_mutex.go:154 +0xad
 internal/poll.(*FD).writeLock(...)
 	/usr/lib/go-1.13/src/internal/poll/fd_mutex.go:239
 internal/poll.(*FD).Write(0xc000075ce0, 0xc00052f5c0, 0x39, 0x40, 0x0, 0x0, 0x0)
 	/usr/lib/go-1.13/src/internal/poll/fd_unix.go:255 +0x5e
 os.(*File).write(...)
 	/usr/lib/go-1.13/src/os/file_unix.go:276
 os.(*File).Write(0xc000010240, 0xc00052f5c0, 0x39, 0x40, 0x38, 0xc00052f5c0, 0x1b)
 	/usr/lib/go-1.13/src/os/file.go:153 +0x77
 log.(*Logger).Output(0xc0004a6d20, 0x2, 0xc00029c5a0, 0x1d, 0x0, 0x0)
 	/usr/lib/go-1.13/src/log/log.go:172 +0x287
 log.(*Logger).Printf(0xc0004a6d20, 0xb92ed8, 0x1d, 0x0, 0x0, 0x0)
 	/usr/lib/go-1.13/src/log/log.go:179 +0x7e
```

**Comment by kalafut** [comment]
Regarding blocking on stderr, has the test been run outside of docker? I recall some issues with stderr hanging up in docker, though perhaps that has been addressed.

**Comment by mr-tron** [comment]
No. I reproduce it locally without docker or limits on stdout/stderr. 
I will try to remove all logs except errors. Maybe it can be used as workarround while we search correct fix.

**Comment by mr-tron** [comment]
I don't understand why but commit https://github.com/Venafi/vcert/commit/3a7b449f1fac081d73be795e0e4cdd27a656bfac fixed problem.

**Comment by tr1ck3r** [comment]
@kalafut @mr-tron I don't consider removal of logging a fix but hopefully this finding gets us closer to a permanent solution.  Thank you for your efforts, please continuing working together on this issue until we have a plugin that is both stable and maintainable.

**Comment by mbrancato** [comment]
Is it possible that stdout and stderr from the plugin was somehow not accessible due to how Vault handles plugins? If so, maybe these should use some logging interface provided by Vault?

**Comment by tr1ck3r** [comment]
@kalafut investigated the logging issue and has provided the following explanation:
> I wanted to provide a little background on why replacing the custom logger (e.g. "log.New(...)")  with "log.Println(...)" on branch https://github.com/Venafi/vcert/commits/test-close-connection helped, because it's not obvious from just looking at those functions. Both of them write output to os.Stderr, so they look nearly equivalent. The issue is that when running plugins, go-plugin remaps the global os.Stdio and os.Stderr to internal pipes for redirection. The use of these redirections files isn't present for gRPC however (see: https://github.com/hashicorp/go-plugin/issues/93), so the writes to the pipe go nowhere and can end up blocking depending how the mutex is handled at the file level. This is what was happening to the "log.New()" calls, since they're creating loggers based on the new, remapped os.Stderr/Stdio files.
> 
> While the remapped files won't work, writing to the original Stderr/Stdio does. That's why the log.Println() solution works. That logger is created before the remapping, and always references the original os.Stderr. This is also how other custom loggers (e.g. go-hclog) can work, since they're typically configured with the original Stderr/Stdio of the plugin process, before the plugin server starts up and does the remapping.
> 
> This subtlety was new to me too, since our plugin logging almost always uses the framework.Backend object, which already has a configured logger. We either reference it directly, or pass it down to functions, similar to context. Hopefully that helps explain why creating new loggers wasn't working, and why using the global logger should (and does) work.

**Comment by tr1ck3r** [comment]
We have released a new version of the Venafi Monitoring Secret Engine plugin that addresses the stability issue (https://github.com/Venafi/vault-pki-monitor-venafi/releases/tag/v0.5.5).  We ran stress tests using this plugin most of the preceding day and it remained stable and available throughout (the Vault CA issuing/signing 10's of thousands of RSA and EC certificates).  

We changed the default number of import workers in this version from 3 to 12 to better drain the queue when the rate of certificates being issued by Vault is high.  This will necessarily put the TPP REST API (WebSDK) under heavier load so customers will want to pay more attention there.  The number of workers can be tuned using the `venafi_import_workers` parameter of the Vault PKI roles (we don’t recommend going much higher than 12 but going lower would make sense for less active Vault CAs).
