### ISSUE TITLE
400 Grant Token has been revoked, has expired, or the refresh token is invalid

### ISSUE THREAD

**Issue by DylanWoodrow** [Venafi/vault-pki-monitor-venafi#82]
Writing an issue report on behalf of a Venafi customer making use of this tool.

Customer is experiencing a `400 Grant Token has been revoked, has expired, or the refresh token is invalid` error when attempting step 10 of the readme. Token is valid from the Venafi side, and can successfully authenticate outside of this tool. Resetting the tool and walking back through setup tasks still has not allowed the customer to successfully proceed. 

Customer is using version 20.3 of TPP. Let me know what other information I can provide to aid diagnosis and troubleshooting.

**Comment by tr1ck3r** [comment]
Thanks @DylanWoodrow.  I'm assuming they're seeing the `400 Grant Token has been revoked, has expired, or the refresh token is invalid` error in the Vault log, right?  Is that actually preventing the `vault-pki-monitor-venafi` from working (enforcing policy and/or pushing issued certificates into TPP)?  The way this solution was designed it immediately uses the refresh token (if provided) to obtain a new pair of tokens.  If there are multiple Vault servers (i.e. a cluster) then obviously only one will be able to successfully perform that task and the others would get the 400 error... but once that new access token is obtained and the venafi secret is updated, all the Vault servers should be able to use it.  That's a long winded way of saying it is expected behavior to see those errors in the Vault log when our solution is in the process of obtaining a new pair of tokens.

**Comment by tr1ck3r** [comment]
Thanks for the clarification.  So that's the expected behavior.  The first time that command is executed, the refresh token is used by our solution to obtain a new pair of tokens (security consideration ensuring that no one other than this venafi secret in Vault can use this grant).  There's no need to execute that command again unless you want to change to a different grant.

**Comment by DylanWoodrow** [comment]
Update from the customer:

```
I removed and reinstated a vault appRole on the box and apparently that fixed the issue. I can now configure the plugin and issue the certs. I am don’t what the root cause is here. I’ll do a some more testing to verify everything is working as expected and update you guys on how it goes.
```

It looks like the original role may have been corrupting secrets, judging by the previous errors and troubleshooting we went through. Is there anything further that can and should be done to diagnose why this was happening to begin with?
